### ISSUE TITLE
Could you tell us how to convert the blob files

### ISSUE THREAD

**Issue by yuchenlichuck** [ibaiGorordo/depthai-TopFormer-Semantic-Segmentation#2]
Hi, there, I am not familiar with mmseg, could you help me fix a issue.
I trained the topformer model with my customer dataset and the output is one hot code embedding (150X512X512), how could we output the predict labels seg map (512X512)?

**Comment by ibaiGorordo** [comment]
You can use np.argmax on the first dimension to get the label of each pixel

**Comment by yuchenlichuck** [comment]
Thank you!
